#!/usr/bin/env node

const PROCESS = require('process');
const { Client } = require('pg');
const READLINE = require('readline');

function logAndExit(err) {
  console.log(err);
  process.exit(1);
}

class ExpenseData {
  constructor() {
    this.client = new Client({ database: 'expenses' });
  }

  displayExpenses(response) {
    response.rows.forEach(row => {
      let columns = [
        `${row.id}`.padStart(3),
        row.created_on.toDateString().padStart(10),
        row.amount.padStart(12),
        row.memo
      ];

      console.log(columns.join(' | '));
    });
  }

  async listExpenses() {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let res = await this.client.query("SELECT * FROM expenses ORDER BY created_on ASC")
      .catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    this.displayExpenses(res);
    if (res.rowCount > 1) {
      this.displayTotal(res.rows);
    }

    await this.client.end().catch(err => logAndExit(err));
  }

  async addExpense(amount, memo) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let date = new Date().toLocaleDateString();

    let queryText = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)';
    let queryValues = [amount, memo, date];

    await this.client.query(queryText, queryValues).catch(err => logAndExit(err));

    await this.client.end().catch(err => logAndExit(err));
  }

  async searchExpenses(searchItem) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let queryText = 'SELECT * FROM expenses WHERE memo ILIKE $1';
    let queryValue = [`%${searchItem}%`];

    let res = await this.client.query(queryText, queryValue).catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    this.displayExpenses(res);
    if (res.rowCount > 1) {
      this.displayTotal(res.rows);
    }

    await this.client.end().catch(err => logAndExit(err));
  }

  async deleteExpense(itemID) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let queryText = 'SELECT * FROM expenses WHERE id = $1';
    let res = await this.client.query(queryText, [itemID]).catch(err => logAndExit(err));

    if (res.rowCount === 1) {
      let deleteText = 'DELETE FROM expenses WHERE id = $1';
      await this.client.query(deleteText, [itemID]).catch(err => logAndExit(err));

      console.log('The following expense has been deleted:');
      this.displayExpenses(res);
    } else {
      console.log(`There is no expense with the id '${itemID}'`);
    }

    await this.client.end().catch(err => logAndExit(err));
  }

  async deleteAllExpenses() {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    await this.client.query('DELETE FROM expenses').catch(err => logAndExit(err));
    console.log('All expenses have been deleted.');

    await this.client.end().catch(err => logAndExit(err));
  }

  displayCount(count) {
    if (count === 0) {
      console.log('There are no expenses');
    } else {
      let verb = count > 1 ? 'are' : 'is';
      let countableNoun = count > 1 ? 'expenses' : 'expense';
      console.log(`There ${verb} ${count} ${countableNoun}.`);
    }
  }

  displayTotal(expenses) {
    let total = expenses.reduce((acc, row) => acc + Number(row.amount), 0);

    console.log('-'.repeat(50));
    console.log(`Total ${String(total).padStart(30)}`);
  }

  async setupSchema() {
    let tableExistsQuery = `Select COUNT(*) FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'expenses'`;

    let tableCreationQuery = `CREATE TABLE expenses (
      id serial PRIMARY KEY,
      amount numeric(6,2) NOT NULL,
      memo text NOT NULL,
      created_on date NOT NULL
    )`;

    let res = await this.client.query(tableExistsQuery).catch(err => logAndExit(err));

    if (res.rows[0].count === '0') {
      await this.client.query(tableCreationQuery).catch(err => logAndExit(err));
    }
  }
}

class CLI {
  constructor() {
    this.application = new ExpenseData();
  }

  static HELP() {
    return `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`;
  }

  displayHelp() {
    console.log(CLI.HELP());
  }

  run(args) {
    let command = args[2];

    if (command === 'list') {
      this.application.listExpenses();
    } else if (command === 'add') {
      let amount = args[3];
      let memo = args[4];
      if (amount && memo) {
        this.application.addExpense(amount, memo);
      } else {
        console.log('You must provide an amount and memo.');
      }
    } else if (command === 'search') {
      let searchItem = args[3];
      if (searchItem) {
        this.application.searchExpenses(searchItem);
      } else {
        console.log('You must provide a search term.');
      }
    } else if (command === 'delete') {
      let deleteID = args[3];
      if (deleteID) {
        this.application.deleteExpense(deleteID);
      } else {
        console.log('You must provide the ID of the expense you wish to delete.');
      }
    } else if (command === 'clear') {
      let rl = READLINE.createInterface({
        input: process.stdin,
        output: process.stdout
      });
      let questionText = 'This will remove all expenses. Are you sure? (y/n) ';
      rl.question(questionText, (answer) => {
        if (answer === 'y') {
          this.application.deleteAllExpenses();
        }
        rl.close();
      });
    } else {
      this.displayHelp();
    }
  }
}

let cli = new CLI();
cli.run(PROCESS.argv);